# Situación problema

### Players FIFA 21

La base de datos a utilizar contiene los atributos de 30 jugadores de futbol, basados en las cartas de modo carrera del videojuego FIFA 21

A través de su análisis y aplicación de elementos gráficos, se responderán 5 preguntas/hipótesis planteadas

https://www.kaggle.com/stefanoleone992/fifa-21-complete-player-dataset

### Limpieza de la base de datos

In [1]:
pip install seaborn

Requirement already satisfied: seaborn in /srv/conda/envs/notebook/lib/python3.7/site-packages (0.11.2)
Requirement already satisfied: pandas>=0.23 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from seaborn) (1.0.4)
Requirement already satisfied: matplotlib>=2.2 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from seaborn) (3.2.1)
Requirement already satisfied: numpy>=1.15 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from seaborn) (1.18.5)
Requirement already satisfied: scipy>=1.0 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from seaborn) (1.4.1)
Requirement already satisfied: python-dateutil>=2.1 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from matplotlib>=2.2->seaborn) (2.8.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from matplotlib>=2.2->seaborn) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from matplotlib>=2.2->seaborn) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from matplotlib>=2.2->seaborn) (0.10.0)
Requirement already satisfied: six in /srv/conda/envs/notebook/lib/python3.7/site-packages (from cycler>=0.10->matplotlib>=2.2->seaborn) (1.16.0)
Requirement already satisfied: pytz>=2017.2 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pandas>=0.23->seaborn) (2020.1)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
%ls

 00_00_binder.ipynb                     datasets/
 00_00_primer_pasos.ipynb               players_fifa21.csv
 01_01_data_types.ipynb                'Proyecto (2).ipynb'
 01_02_read_iloc_unique_groupby.ipynb  'Proyecto (4).ipynb'
 02_00_data_wrangling.ipynb            'Proyecto (5).ipynb'
 02_01_null_display.ipynb               Proyecto.ipynb
 02_02_basic_math.ipynb                 Quiz3P2.ipynb
 Clase1.ipynb                           Quiz5_Intento2.ipynb
'Clase4 (1).ipynb'                      README.md
 Clase5.ipynb                           requirements.txt

In [4]:
df = pd.read_csv('players_fifa21.csv')
df.head(10)

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club_name,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,33,24/06/1987,170,72,Argentina,FC Barcelona,...,66+3,65+3,65+3,65+3,66+3,62+3,52+3,52+3,52+3,62+3
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,35,05/02/1985,187,83,Portugal,Juventus,...,65+3,61+3,61+3,61+3,65+3,61+3,54+3,54+3,54+3,61+3
2,200389,https://sofifa.com/player/200389/jan-oblak/210002,J. Oblak,Jan Oblak,27,07/01/1993,188,87,Slovenia,Atlético Madrid,...,32+3,36+3,36+3,36+3,32+3,32+3,33+3,33+3,33+3,32+3
3,188545,https://sofifa.com/player/188545/robert-lewand...,R. Lewandowski,Robert Lewandowski,31,21/08/1988,184,80,Poland,FC Bayern München,...,64+3,65+3,65+3,65+3,64+3,61+3,60+3,60+3,60+3,61+3
4,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Júnior,28,05/02/1992,175,68,Brazil,Paris Saint-Germain,...,67+3,62+3,62+3,62+3,67+3,62+3,49+3,49+3,49+3,62+3
5,192985,https://sofifa.com/player/192985/kevin-de-bruy...,K. De Bruyne,Kevin De Bruyne,29,28/06/1991,181,70,Belgium,Manchester City,...,79+3,80+3,80+3,80+3,79+3,75+3,69+3,69+3,69+3,75+3
6,231747,https://sofifa.com/player/231747/kylian-mbappe...,K. Mbappé,Kylian Mbappé Lottin,21,20/12/1998,178,73,France,Paris Saint-Germain,...,67+3,63+3,63+3,63+3,67+3,63+3,55+3,55+3,55+3,63+3
7,192448,https://sofifa.com/player/192448/marc-andre-te...,M. ter Stegen,Marc-André ter Stegen,28,30/04/1992,187,85,Germany,FC Barcelona,...,33+3,41+3,41+3,41+3,33+3,31+3,33+3,33+3,33+3,31+3
8,203376,https://sofifa.com/player/203376/virgil-van-di...,V. van Dijk,Virgil van Dijk,28,08/07/1991,193,92,Netherlands,Liverpool,...,80+3,85+3,85+3,85+3,80+3,82+3,89+2,89+2,89+2,82+3
9,212831,https://sofifa.com/player/212831/alisson-ramse...,Alisson,Alisson Ramsés Becker,27,02/10/1992,191,91,Brazil,Liverpool,...,31+3,35+3,35+3,35+3,31+3,30+3,30+3,30+3,30+3,30+3

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Columns: 106 entries, sofifa_id to rb
dtypes: float64(15), int64(48), object(43)
memory usage: 25.0+ KB

In [6]:
df.columns

Index(['sofifa_id', 'player_url', 'short_name', 'long_name', 'age', 'dob',
       'height_cm', 'weight_kg', 'nationality', 'club_name',
       ...
       'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb'],
      dtype='object', length=106)

In [7]:
df = df.drop(['sofifa_id', 'player_url','long_name','dob','lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb'], axis=1)
df.head(3)

,short_name,age,height_cm,weight_kg,nationality,club_name,league_name,league_rank,overall,potential,...,rf,rw,lam,cam,ram,lm,lcm,cm,rcm,rm
0,L. Messi,33,170,72,Argentina,FC Barcelona,Spain Primera Division,1,93,93,...,93+0,92+0,93+0,93+0,93+0,91+2,87+3,87+3,87+3,91+2
1,Cristiano Ronaldo,35,187,83,Portugal,Juventus,Italian Serie A,1,92,92,...,91+0,89+0,88+3,88+3,88+3,88+3,81+3,81+3,81+3,88+3
2,J. Oblak,27,188,87,Slovenia,Atlético Madrid,Spain Primera Division,1,91,93,...,35+0,32+0,38+3,38+3,38+3,35+3,38+3,38+3,38+3,35+3

In [8]:
df.columns

Index(['short_name', 'age', 'height_cm', 'weight_kg', 'nationality',
       'club_name', 'league_name', 'league_rank', 'overall', 'potential',
       'value_eur', 'wage_eur', 'player_positions', 'preferred_foot',
       'international_reputation', 'weak_foot', 'skill_moves', 'work_rate',
       'body_type', 'real_face', 'release_clause_eur', 'player_tags',
       'team_position', 'team_jersey_number', 'loaned_from', 'joined',
       'contract_valid_until', 'nation_position', 'nation_jersey_number',
       'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic',
       'gk_diving', 'gk_handling', 'gk_kicking', 'gk_reflexes', 'gk_speed',
       'gk_positioning', 'player_traits', 'attacking_crossing',
       'attacking_finishing', 'attacking_heading_accuracy',
       'attacking_short_passing', 'attacking_volleys', 'skill_dribbling',
       'skill_curve', 'skill_fk_accuracy', 'skill_long_passing',
       'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed',
       'movement_agility', 'movement_reactions', 'movement_balance',
       'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength',
       'power_long_shots', 'mentality_aggression', 'mentality_interceptions',
       'mentality_positioning', 'mentality_vision', 'mentality_penalties',
       'mentality_composure', 'defending_marking', 'defending_standing_tackle',
       'defending_sliding_tackle', 'goalkeeping_diving',
       'goalkeeping_handling', 'goalkeeping_kicking',
       'goalkeeping_positioning', 'goalkeeping_reflexes', 'ls', 'st', 'rs',
       'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm',
       'rcm', 'rm'],
      dtype='object')

In [9]:
df = df.drop(['league_rank','wage_eur','player_positions','ls', 'st', 'rs','lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 
              'preferred_foot','international_reputation', 'weak_foot', 'skill_moves', 'work_rate','cm','rcm', 'rm','body_type', 'real_face', 
              'release_clause_eur', 'player_tags', 'team_position', 'team_jersey_number', 'loaned_from','joined','contract_valid_until', 
              'nation_position', 'nation_jersey_number','gk_diving', 'gk_handling', 'gk_kicking', 'gk_reflexes', 'gk_speed', 'gk_positioning', 
              'player_traits', 'attacking_crossing','attacking_finishing', 'attacking_heading_accuracy','attacking_short_passing', 'attacking_volleys', 
              'skill_dribbling','skill_curve', 'skill_fk_accuracy', 'skill_long_passing','skill_ball_control', 'movement_acceleration', 'movement_sprint_speed',
              'movement_agility', 'movement_reactions', 'movement_balance','power_shot_power', 'power_jumping', 'power_stamina', 'power_strength',
              'power_long_shots', 'mentality_aggression', 'mentality_interceptions','mentality_positioning', 'mentality_vision', 'mentality_penalties',
              'mentality_composure', 'defending_marking', 'defending_standing_tackle','defending_sliding_tackle', 'goalkeeping_diving','goalkeeping_handling', 
              'goalkeeping_kicking','goalkeeping_positioning', 'goalkeeping_reflexes','height_cm','weight_kg','club_name','potential','pace','passing',
              'dribbling','physic'], axis=1)
df.head()

,short_name,age,nationality,league_name,overall,value_eur,shooting,defending
0,L. Messi,33,Argentina,Spain Primera Division,93,67500000,92.0,38.0
1,Cristiano Ronaldo,35,Portugal,Italian Serie A,92,46000000,93.0,35.0
2,J. Oblak,27,Slovenia,Spain Primera Division,91,75000000,NaN,NaN
3,R. Lewandowski,31,Poland,German 1. Bundesliga,91,80000000,91.0,43.0
4,Neymar Jr,28,Brazil,French Ligue 1,91,90000000,85.0,36.0

In [10]:
df = df.dropna()
df.head()

,short_name,age,nationality,league_name,overall,value_eur,shooting,defending
0,L. Messi,33,Argentina,Spain Primera Division,93,67500000,92.0,38.0
1,Cristiano Ronaldo,35,Portugal,Italian Serie A,92,46000000,93.0,35.0
3,R. Lewandowski,31,Poland,German 1. Bundesliga,91,80000000,91.0,43.0
4,Neymar Jr,28,Brazil,French Ligue 1,91,90000000,85.0,36.0
5,K. De Bruyne,29,Belgium,English Premier League,91,87000000,86.0,64.0

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23 entries, 0 to 29
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   short_name   23 non-null     object
 1   age          23 non-null     int64
 2   nationality  23 non-null     object
 3   league_name  23 non-null     object
 4   overall      23 non-null     int64
 5   value_eur    23 non-null     int64
 6   shooting     23 non-null     float64
 7   defending    23 non-null     float64
dtypes: float64(2), int64(3), object(3)
memory usage: 1.6+ KB

In [12]:
#df.describe()

In [13]:
df.columns

Index(['short_name', 'age', 'nationality', 'league_name', 'overall',
       'value_eur', 'shooting', 'defending'],
      dtype='object')

### Descripción de las variables de interés

Las variables de interés son short_name, age, overall, league_name, nationality, shooting, defending y value_eur
* short_name es una variable categórica que describe el nombre de cada jugador
* age es una variable numérica discreta que explica la edad en años del jugador
* nationality es una variable categórica que describe la nacionalidad del jugador
* league_name es una variable categórica que describe la liga en la que se juega
* overall es una variable numérica discreta que explica la puntuación general del jugador en una escala del 1-100
* value_eur es una variable numérica discreta que explica el valor del jugador en euros
* shooting es una variable numérica discreta que califica el tiro del jugador en una escala del 1-100
* defending es una variable numérica discreta que califica las habilidades defensivas del jugador en una escala del 1-100

In [20]:
#df['value_eur'].plot(kind='hist', figsize=(15,8))

In [15]:
#Existe una correlación entre la edad y el overall

In [16]:
#Los jugadores de La Liga son mejores que los jugadores de la Premier League

In [17]:
#Los jugadores argentinos tienen mejor shooting que los ingleses

In [18]:
#En la variable defensa existe un sesgo a la izquierda, debido a que los mejores ratings pertenecen a delanteros y medios

In [19]:
#El valor promedio de los jugadores de la serie A es mayor al de la Bundesliga